name: CI/CD

on:
  push:
    branches: [ "ci-cd-pipeline" ]
  pull_request:
    branches: [ "ci-cd-pipeline" ]

jobs:
  client-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build
        env:
          CI: false
        run: npm run build
      - name: Run linter
        run: npm run lint > lint-report.txt || true
      - name: Run tests with coverage
        run: npm test -- --coverage
      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: client-lint-report
          path: ./client/lint-report.txt
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: client-test-coverage
          path: ./client/coverage

  server-job:
    runs-on: ubuntu-latest
    needs: client-job
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build
        env:
          CI: false
        run: npm run build
      - name: Run linter
        run: CI=false npm run lint
      - name: Run tests
        run: npm test

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: server-job
    if: github.ref == 'refs/heads/ci-cd-pipeline' && github.event_name == 'push'
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}