name: Main CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install server dependencies, Build, Test
    - run: cd server && npm install
    - run: cd server && npm run build --if-present
    - run: cd server && npm test
    - name: Install client dependencies, Build & Test
    - run: cd client && npm install
    - run: cd client && npm run build --if-present
    - run: cd client && npm test
